#!/bin/sh
echo "You must have mplayer/mencoder installed to use this (yum install mplayer)"
mencoder mf://image0*png -mf fps=25:type=png -ovc lavc -lavcopts vcodec=msmpeg4v2:mbd=2:trell -oac copy -o simulation.mpeg
mplayer -loop 0 simulation.mpeg
