import glob
import os

curdir = os.getcwd()

os.chdir('../')
files = glob.glob('*.cpp') 
os.chdir(curdir)

testfiles = glob.glob('../tests/Test*.hpp')


base  = '-Icxxtest -Idatawriters -Iheart -I. '

petsc_base = '../../petsc-2.2.1/'
petsc_inc = '-I'+petsc_base+'include '
petsc_bmake = '-I'+petsc_base+'bmake/linux-gnu '
petsc_mpi = '-I'+petsc_base+'include/mpiuni '
petsc_incs = petsc_inc+petsc_bmake+petsc_mpi

petsc_libpath = '#'+petsc_base+'lib/libg_c++/linux-gnu/'


all_libs= ['petscts', 'petscsnes', 'petscksp', 'petscdm', 
'petscmat', 'petscvec', 'petsc', 'datawriter','heart','ode']


opt = Environment(CCFLAGS = base+petsc_incs,BOPT='g_c++',CXX='/usr/bin/g++')
test = Builder(action = 'cxxtest/cxxtestgen.pl --error-printer -o $TARGET $SOURCES')
runtests = Builder(action = './$SOURCE | tee $TARGET')

opt['BUILDERS']['Test'] = test
opt['BUILDERS']['RunTests'] = runtests
opt['ENV']['LD_LIBRARY_PATH'] = petsc_base+'lib/libg_c++/linux-gnu/'

opt.Library('heart',files)
opt.Test('runner.cpp',testfiles) 
opt.Program('testrunner',['runner.cpp'], LIBS=all_libs,LIBPATH=['../../datawriters/build', '../../odes/build', '.', petsc_libpath])
opt.RunTests('build.log','testrunner')

