import glob
import os

curdir = os.getcwd()

os.chdir('../')
files = glob.glob('*.cpp') 
os.chdir(curdir)

testfiles = glob.glob('../tests/Test*.hpp')
os.chdir('../')
testsource = glob.glob('tests/*.cpp')
os.chdir(curdir)

Import("*")

opt = Environment(CCFLAGS = extra_flags, CXX=cxx, AR=ar)
opt.Replace(CPPPATH = Split('#/cxxtest #/datawriters #/. #/datawriters/tests'))
test = Builder(action = 'cxxtest/cxxtestgen.pl --error-printer -o $TARGET $SOURCES')
runtests = Builder(action = './$SOURCE | tee $TARGET')

opt.Append(LINKFLAGS = link_flags)

opt['BUILDERS']['Test'] = test
opt['BUILDERS']['RunTests'] = runtests

opt.Library('testdatawriter',testsource)
opt.Library('datawriter',files)
opt.Test('runner.cpp',testfiles) 

opt.Program('testrunner',['runner.cpp'], LIBS=['datawriter','testdatawriter'],LIBPATH=['.'])
opt.RunTests('build.log','testrunner')
