function newData1 = importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified chaste output file
%  Auto-generated by MATLAB on 27-Aug-2009 17:00:31

% Import the file
newData1 = importdata(fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end