import glob
import os

curdir = os.getcwd()

os.chdir('../')
files = glob.glob('*.cpp') 
os.chdir(curdir)

testfiles = glob.glob('../tests/Test*.hpp')
os.chdir('../')
testsource = glob.glob('tests/*.cpp')
os.chdir(curdir)


Import("*")


all_libs= ['petscts', 'petscsnes', 'petscksp', 'petscdm', 
'petscmat', 'petscvec', 'petsc', 'datawriter','ode','testode']


opt = Environment(CCFLAGS = petsc_incs+extra_flags,BOPT='g_c++',CXX=cxx,AR=ar)
opt.Replace(CPPPATH = Split('#/cxxtest #/datawriters #/odes #/. #/odes/tests'))
test = Builder(action = 'cxxtest/cxxtestgen.pl --error-printer -o $TARGET $SOURCES')
runtests = Builder(action = './$SOURCE | tee $TARGET')


opt.Append(LINKFLAGS = link_flags)


opt['BUILDERS']['Test'] = test
opt['BUILDERS']['RunTests'] = runtests
opt['ENV']['LD_LIBRARY_PATH'] = petsc_base+'lib/libg_c++/linux-gnu/'

opt.Library('ode',files)
opt.Library('testode',testsource)
opt.Test('runner.cpp',testfiles) 
opt.Program('testrunner',['runner.cpp'], LIBS=all_libs,LIBPATH=['../../datawriters/build', '.', petsc_libpath])
opt.RunTests('build.log','testrunner')

