#ifndef CELLLUO_RUDY_1991FROMCELLML_HPP_
#define CELLLUO_RUDY_1991FROMCELLML_HPP_

//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: luo_rudy_1991
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translate: 8040, pycml: 7844)
//! on Wed Feb 17 11:08:48 2010
//! 
//! <autogenerated>

#include "AbstractCardiacCell.hpp"
#include "AbstractStimulusFunction.hpp"

class Cellluo_rudy_1991FromCellML : public AbstractCardiacCell
{
    
public:
    Cellluo_rudy_1991FromCellML(boost::shared_ptr<AbstractIvpOdeSolver> pSolver, boost::shared_ptr<AbstractStimulusFunction> pIntracellularStimulus);
    ~Cellluo_rudy_1991FromCellML();
    void VerifyStateVariables();
    double GetIIonic();
    void EvaluateYDerivatives(double var_environment__time, const std::vector<double>& rY, std::vector<double>& rDY);
};


#endif // CELLLUO_RUDY_1991FROMCELLML_HPP_
