#ifdef CHASTE_CVODE
#ifndef CELLLUO_RUDY_1991FROMCELLMLCVODE_HPP_
#define CELLLUO_RUDY_1991FROMCELLMLCVODE_HPP_

//! @file
//! 
//! This source file was generated from CellML.
//! 
//! Model: luo_rudy_1991
//! 
//! Processed by pycml - CellML Tools in Python
//!     (translate: 8117, pycml: 8095)
//! on Fri Mar  5 16:18:44 2010
//! 
//! <autogenerated>

#include "AbstractCvodeCell.hpp"
#include "AbstractStimulusFunction.hpp"

class Cellluo_rudy_1991FromCellMLCvode : public AbstractCvodeCell
{
    
public:
    Cellluo_rudy_1991FromCellMLCvode(boost::shared_ptr<AbstractIvpOdeSolver> pOdeSolver /* unused; should be empty */, boost::shared_ptr<AbstractStimulusFunction> pIntracellularStimulus);
    ~Cellluo_rudy_1991FromCellMLCvode();
    void VerifyStateVariables();
    double GetIIonic();
    void EvaluateRhs(double var_environment__time, const N_Vector rY, N_Vector rDY);
};


#endif // CELLLUO_RUDY_1991FROMCELLMLCVODE_HPP_
#endif // CHASTE_CVODE
